//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominionData.DataAndBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerAddress
    {
        public int CustomerAddressId { get; set; }
        public int CustomerId { get; set; }
        public string Address1 { get; set; }
        public string Addrtess2 { get; set; }
        public string PostCode { get; set; }
        public string Suburb { get; set; }
        public int AddressTypeId { get; set; }
    
        public virtual AddressType AddressType { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
